### ISSUE TITLE
Format disapears when players type too fast

### ISSUE THREAD

**Issue by Mowzy-Graphics** [PlanetTeamSpeakk/Chattix#10]
when submitting a message too fast (preview can't keep up) the message will appear without any format and any username.
As if it had been a /tellraw command.

Here are some images to better explain :

When the preview has time to update :
![[IMAGE]](https://i.ibb.co/cQZhFDT/111111.png)

When the preview doesn't have time to load :
![[IMAGE]](https://i.ibb.co/sJxMfLg/222222.png)

On the console :
![[IMAGE]](https://i.ibb.co/7QKQz86/3333333.png)

Here's a list of all the mods i use :

[https://yellow-maighdiln-25.tiiny.site](https://yellow-maighdiln-25.tiiny.site)

And here's a log from launch :

[https://mclo.gs/pAg6eaI](https://mclo.gs/pAg6eaI)

**Comment by PlanetTeamSpeakk** [comment]
I fear that's a limitation of Minecraft's chat signing feature. You have to give the message time to be signed before sending it, otherwise the signature doesn't correspond to the message and the server/other players cannot verify it.

**Comment by Mowzy-Graphics** [comment]
Is there a way to make the player wait for the signing to happen before beeing able to send the message ?
Now that my server is open, it's very frustrating not knowing who's talking...

**Comment by PlanetTeamSpeakk** [comment]
There's a setting on the client regarding when messages get signed. You can set that to sign when sending it to the server after which the server will decorate it, send it back to the client and the client can then confirm it. Rather annoying if you ask me, but this entire chat signing stuff is anyway.

**Comment by PlanetTeamSpeakk** [comment]
I believe this should be fixed in the next update. I am currently porting the mod to 1.19.3 and Mojang removed chat previews. This means that the client does not have to wait to receive the decorated version from the server anymore before sending the message which should fix this issue. I have tried this on my own local test server and it appeared to be fine, but I obviously cannot say with certainty that this issue is now resolved.

There is virtually nothing I can do to fix this in the current version because this is a limitation of Minecraft's chat signing system (which thus seems fixed in 1.19.3), so if you really need a version for 1.19.2, there is sadly nothing I can do for you.

I will hereby close this issue, if you still encounter this in the next version which I will release hopefully somewhere in the coming days/weeks, please open a new one.
