### ISSUE TITLE
[1.19.2 / FORGE] If you send your message too soon after typing the formatting disappears.

### ISSUE THREAD

**Issue by murao-kun** [PlanetTeamSpeakk/Chattix#3]
If you type your message and pressing enter to send it too fast, the message loosing it's formatting.
The issue is not happening if you wait around 2 seconds after typing.
![image](https://user-images.githubusercontent.com/110398598/196242372-42ec0fb4-c3a4-4664-8d7e-faf6173e187e.png)

**Comment by PlanetTeamSpeakk** [comment]
That's because you don't give the server time to let you sign the message.
The message you're typing has to be send to the server, formatted, sent back to you to sign and sent to the server again, but signed and formatted. There's sadly nothing Chattix can do to speed up this process and because of this signing system Minecraft added, the message has to be signed for other people to see it in its formatted form too.

If the delay is an issue for you, you can set chat preview to only preview upon sending, this can be changed in Minecraft's chat settings.
