### ISSUE TITLE
Private message customizations

### ISSUE THREAD

**Issue by ChristopherHaws** [PlanetTeamSpeakk/Chattix#5]
Hey there and thanks for the mod!

I would love to be able to customize the private message (/msg) text so in some of the following ways:
- Remove the italics
- Customize the message template (so that it doesn't say `{player} whispered to you: {message}`)
- Add custom colors and formatting to the message template
- Add a sound that plays when you receive a private message

Additionally it would be awesome if you could use the command `/reply` or `/r` to respond to the last private message you recieved.

Thanks!

**Comment by PlanetTeamSpeakk** [comment]
I was working on this already. Due to a limitation caused by the signing stuff Minecraft now does, however, if you'd want this to be modifiable, both the send and receive format would have to be the same which I'm personally not fond of.
There is one way to do so, but it'd probably require a server restart, or at the very least a relog of every player to apply modifications.

**Comment by ChristopherHaws** [comment]
As long as it is documented, I wouldn't mind it requiring a server restart. ^_^

**Comment by PlanetTeamSpeakk** [comment]
Added in an upcoming version
