### ISSUE TITLE
Parse luckperm placeholders before parsing formatting

### ISSUE THREAD

**Issue by ChristopherHaws** [PlanetTeamSpeakk/Chattix#6]
I am trying to setup prefix formatting using luckperms with the following but the result is that it prints out `<color:red>` instead of it turning the font red.

```
<color:%luckperms_group_meta:prefix-color%>%luckperms_prefix%</color>
```
![image](https://user-images.githubusercontent.com/5934505/203514536-e1f5dc4b-2bd0-43a2-8b10-f81924ff387e.png)

**Comment by PlanetTeamSpeakk** [comment]
Hmm, I guess that would be a result of placeholders being parsed after the minimessage format.

**Comment by PlanetTeamSpeakk** [comment]
Fixed in an upcoming version. Certain placeholders will now be parsed before the minimessage format gets parsed. This includes the luckperms group/user meta placeholders, the name placeholder, the old name placeholder and the world placeholder.

P.S. you can of course just include the colour of the prefix of a group in the prefix itself using something like `&c&lAdmin`.
